from typing import List, Dict, Any

from app.schemas import StoryPanel


# =========================================================
# BUILD COMIC LAYOUT
# =========================================================

def build_layout(
    story: List[StoryPanel],
    image_paths: List[str]
) -> List[Dict[str, Any]]:
    """
    Combine the generated story panels with their
    corresponding generated image paths.

    Parameters
    ----------
    story:
        List of StoryPanel objects generated by Gemini.

    image_paths:
        List of browser-accessible image URLs.

    Returns
    -------
    List[Dict[str, Any]]
        Final comic layout used by the frontend
        and PDF exporter.
    """

    # =====================================================
    # VALIDATE INPUT
    # =====================================================

    if not story:

        raise ValueError(
            "Cannot build comic layout because "
            "the story contains no panels."
        )

    if not image_paths:

        raise ValueError(
            "Cannot build comic layout because "
            "no generated images were provided."
        )

    # =====================================================
    # CHECK PANEL / IMAGE COUNT
    # =====================================================

    if len(story) != len(image_paths):

        raise ValueError(
            "The number of story panels does not match "
            "the number of generated images. "
            f"Story panels: {len(story)}, "
            f"Images: {len(image_paths)}."
        )

    # =====================================================
    # CREATE FINAL LAYOUT
    # =====================================================

    layout = []

    for index, panel in enumerate(story):

        # -------------------------------------------------
        # GET IMAGE PATH
        # -------------------------------------------------

        image_path = image_paths[index]

        # -------------------------------------------------
        # CONVERT Pydantic MODEL TO DICTIONARY
        # -------------------------------------------------

        if hasattr(
            panel,
            "model_dump"
        ):

            panel_data = panel.model_dump()

        else:

            panel_data = dict(panel)

        # -------------------------------------------------
        # ADD IMAGE PATH
        # -------------------------------------------------

        panel_data["image_path"] = (
            image_path
        )

        # -------------------------------------------------
        # ENSURE PANEL NUMBER
        # -------------------------------------------------

        if not panel_data.get(
            "panel_number"
        ):

            panel_data["panel_number"] = (
                index + 1
            )

        # -------------------------------------------------
        # ENSURE TITLE
        # -------------------------------------------------

        if not panel_data.get(
            "title"
        ):

            panel_data["title"] = (
                f"Panel {index + 1}"
            )

        # -------------------------------------------------
        # ENSURE OPTIONAL TEXT FIELDS
        # -------------------------------------------------

        panel_data.setdefault(
            "scene_description",
            ""
        )

        panel_data.setdefault(
            "caption",
            ""
        )

        panel_data.setdefault(
            "narration",
            ""
        )

        panel_data.setdefault(
            "dialogue",
            ""
        )

        panel_data.setdefault(
            "image_prompt",
            ""
        )

        # -------------------------------------------------
        # ADD TO LAYOUT
        # -------------------------------------------------

        layout.append(
            panel_data
        )

    # =====================================================
    # SORT PANELS
    # =====================================================

    layout.sort(
        key=lambda item: int(
            item.get(
                "panel_number",
                0
            )
        )
    )

    # =====================================================
    # RETURN FINAL LAYOUT
    # =====================================================

    return layout


# =========================================================
# CREATE HTML-FRIENDLY LAYOUT
# =========================================================

def prepare_layout_for_frontend(
    layout: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Prepare the layout for rendering in the frontend.

    This function makes sure every panel contains all
    expected fields.
    """

    frontend_layout = []

    for index, panel in enumerate(
        layout,
        start=1
    ):

        frontend_panel = {

            "panel_number": panel.get(
                "panel_number",
                index
            ),

            "title": panel.get(
                "title",
                f"Panel {index}"
            ),

            "scene_description": panel.get(
                "scene_description",
                ""
            ),

            "image_prompt": panel.get(
                "image_prompt",
                ""
            ),

            "caption": panel.get(
                "caption",
                ""
            ),

            "narration": panel.get(
                "narration",
                ""
            ),

            "dialogue": panel.get(
                "dialogue",
                ""
            ),

            "image_path": panel.get(
                "image_path",
                ""
            )

        }

        frontend_layout.append(
            frontend_panel
        )

    return frontend_layout